### ISSUE TITLE
Compiling the Cloud DB Javascript Server SDK Demo returns errors

### ISSUE THREAD

**Issue by khaledayed** [AppGalleryConnect/agc-demos#16]
I am getting following error for compiling the Cloud DB Js Server:
```TypeError: Cannot read properties of undefined (reading 'getCommonConfiguration')
    at Function.CloudDBSdkUtils.getCloudGwUrl (/home/rosafi-dev/Documents/cloud-db-js/node_modules/@agconnect/database-server/dist/utils/CloudDBSdkUtils.js:34:56)
    at new HttpsCommunicator (/home/rosafi-dev/Documents/cloud-db-js/node_modules/@agconnect/database-server/dist/communicator/https/HttpsCommunicator.js:79:64)
    at AGConnectCloudDB.CloudDBService (/home/rosafi-dev/Documents/cloud-db-js/node_modules/@agconnect/database-server/dist/services/CloudDBService.js:29:30)
    at new AGConnectCloudDB (/home/rosafi-dev/Documents/cloud-db-js/node_modules/@agconnect/database-server/dist/services/AGConnectCloudDB.js:31:28)
    at Function.AGConnectCloudDB.initialize (/home/rosafi-dev/Documents/cloud-db-js/node_modules/@agconnect/database-server/dist/services/AGConnectCloudDB.js:49:37)
    at new CloudDBZoneWrapper (/home/rosafi-dev/Documents/cloud-db-js/src/model/CloudDBZoneWrapper.js:20:32)
    at start (/home/rosafi-dev/Documents/cloud-db-js/src/Start.js:7:32)
    at Object.<anonymous> (/home/rosafi-dev/Documents/cloud-db-js/src/Start.js:57:1)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
CloudDBClient is null, try re-initialize it
CloudDBClient is null, try re-initialize it
CloudDBClient is null, try re-initialize it
CloudDBClient is null, try re-initialize it
CloudDBClient is null, try re-initialize it
CloudDBClient is null, try re-initialize it
queryBooks=> TypeError: Cannot read properties of undefined (reading 'executeQuery')
    at CloudDBZoneWrapper.startAtQuery (/home/rosafi-dev/Documents/cloud-db-js/src/model/CloudDBZoneWrapper.js:141:49)
    at start (/home/rosafi-dev/Documents/cloud-db-js/src/Start.js:37:30)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
queryBooks=> TypeError: Cannot read properties of undefined (reading 'executeAverageQuery')
    at CloudDBZoneWrapper.averageQuery (/home/rosafi-dev/Documents/cloud-db-js/src/model/CloudDBZoneWrapper.js:155:49)
    at start (/home/rosafi-dev/Documents/cloud-db-js/src/Start.js:40:30)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
TypeError: Cannot read properties of undefined (reading 'runTransaction')
    at CloudDBZoneWrapper.deleteOverdueBooks (/home/rosafi-dev/Documents/cloud-db-js/src/model/CloudDBZoneWrapper.js:187:48)
    at start (/home/rosafi-dev/Documents/cloud-db-js/src/Start.js:45:34)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
CloudDBClient is null, try re-initialize it
CloudDBClient is null, try re-initialize it

**Comment by devwithzachary** [comment]
Thank you for the bug report, I shall take a look shortly to see if I can replicate the issue
